[package]
name = "ambient_wasmtime_wasi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
wasmtime = { workspace = true }
wasi-common = { workspace = true }
wasi-cap-std-sync = { workspace = true }

cap-std = "1.0.5"
cap-rand = "1.0.5"
pollster = "0.3.0"
